In [1]:
# These are the packages that we are importing that shall be used throughout this Lab
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn import metrics
import numpy as np

In [2]:
# Read the dataset and look  at the head to gauge the column names and whether column names actually exists
lin_reg_df = pd.read_csv('realestate-1.csv')#YOUR CODE HERE
lin_reg_df.head()

,No,X1 transaction date,X2 house age,X3 distance to the nearest MRT station,X4 number of convenience stores,X5 latitude,X6 longitude,Y house price of unit area
0,1,2012.917,32.0,84.87882,10,24.98298,121.54024,37.9
1,2,2012.917,19.5,306.59470,9,24.98034,121.53951,42.2
2,3,2013.583,13.3,561.98450,5,24.98746,121.54391,47.3
3,4,2013.500,13.3,561.98450,5,24.98746,121.54391,54.8
4,5,2012.833,5.0,390.56840,5,24.97937,121.54245,43.1

In [3]:
# Perform the basic Null Check to decide whether imputation or drop is required
lin_reg_df.isnull().sum()

No                                        0
X1 transaction date                       0
X2 house age                              0
X3 distance to the nearest MRT station    0
X4 number of convenience stores           0
X5 latitude                               0
X6 longitude                              0
Y house price of unit area                0
dtype: int64

In [10]:
# Now rename the column names to make it easy for your own usage - use the rename() function
# Use new column names as: 'SL No', 'Txn_Dt', 'H_Age', 'Distance', 'Conv_stores', 'Lat', 'Long', 'Price_Area'
new_names = zip(lin_reg_df.columns, ['SL No', 'Txn_Dt', 'H_Age', 'Distance', 'Conv_stores', 'Lat', 'Long', 'Price_Area'])
new_names = dict(new_names)

lin_reg_df = lin_reg_df.rename(columns=new_names) #YOUR CODE HERE
lin_reg_df

,SL No,Txn_Dt,H_Age,Distance,Conv_stores,Lat,Long,Price_Area
0,1,2012.917,32.0,84.87882,10,24.98298,121.54024,37.9
1,2,2012.917,19.5,306.59470,9,24.98034,121.53951,42.2
2,3,2013.583,13.3,561.98450,5,24.98746,121.54391,47.3
3,4,2013.500,13.3,561.98450,5,24.98746,121.54391,54.8
4,5,2012.833,5.0,390.56840,5,24.97937,121.54245,43.1
...,...,...,...,...,...,...,...,...
409,410,2013.000,13.7,4082.01500,0,24.94155,121.50381,15.4
410,411,2012.667,5.6,90.45606,9,24.97433,121.54310,50.0
411,412,2013.250,18.8,390.96960,7,24.97923,121.53986,40.6
412,413,2013.000,8.1,104.81010,5,24.96674,121.54067,52.5
413,414,2013.500,6.5,90.45606,9,24.97433,121.54310,63.9

In [18]:
# Split the dataset into target and feature values such that you consider only the
# following features: House Age, Distance to MRT station and Number of Convenience stores
# While we consider Price per Unit Area as the Target variable
y = lin_reg_df[['Price_Area']]#YOUR CODE HERE
X = lin_reg_df[['H_Age', 'Distance', 'Conv_stores']]#YOUR CODE HERE

In [32]:
from sklearn.metrics import mean_squared_error, mean_absolute_error
import numpy as np

# After that test the model with random_state - 0, 50 and 101 and report the one
# that gave the best performance based on MSE, MAE and RMSE
random_state_list = [0, 50, 101]
best_model = None
min_MAE, min_MSE, min_RMSE, best_rdm_st = float('inf'), float('inf'), float('inf'), 0

for rdm_st in random_state_list:

  X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                      train_size=0.75,
                                                      random_state=rdm_st)#YOUR CODE HERE - train-test split: 75 - 25
  model_LR = LinearRegression() #YOUR CODE HERE - init the Linear Regression model
  model_LR.fit(X_train, y_train)#YOUR CODE HERE - fit the data into the model
  y_pred = model_LR.predict(X_test)#YOUR CODE HERE - Predict using this model
  # Use sklearn.metrics to get the values of MAE and MSE
  MAE = mean_absolute_error(y_test, y_pred)#YOUR CODE HERE
  MSE = mean_squared_error(y_test, y_pred)#YOUR CODE HERE
  RMSE = np.sqrt(MSE)#YOUR CODE HERE -- remember RMSE is square root of MSE


  if MAE < min_MAE:
    min_MAE = MAE
    min_MSE = MSE
    min_RMSE = RMSE
    best_rdm_st = rdm_st
    best_model = model_LR

  print("For random state = {}, the values are: ".format(rdm_st))
  print("Mean Absolute Error: ", MAE)
  print("Mean Squared Error: ", MSE)
  print("Root Mean Squared Error: ", RMSE)
  print("========================================================")
  print("\n")

For random state = 0, the values are:
Mean Absolute Error:  6.3585032868023745
Mean Squared Error:  75.17453403521992
Root Mean Squared Error:  8.670324909437934
========================================================


For random state = 50, the values are:
Mean Absolute Error:  7.036525788793118
Mean Squared Error:  81.23659554229282
Root Mean Squared Error:  9.013134612458243
========================================================


For random state = 101, the values are:
Mean Absolute Error:  5.305414282688874
Mean Squared Error:  45.75485998468751
Root Mean Squared Error:  6.764233880099616
========================================================

In [31]:
# Report the random state that gave the best result and the respective values of MAE, MSE and RMSE
# min_MAE, min_MSE, min_RMSE, best_rdm_st
best_st = best_rdm_st # Put the value of best random state here -- 1.1 of Gradescope tests
print(best_st) # -- 1.1
best_MAE = min_MAE # Put the value of best MAE here -- 1.2 of Gradescope tests
print(best_MAE) # -- 1.2
best_MSE = min_MSE # Put the value of best MSE here -- 1.3 of Gradescope tests
print(best_MSE) # -- 1.3
best_RMSE = min_RMSE # Put the value of best RMSE here -- 1.4 of Gradescope tests
print(best_RMSE) # -- 1.4
# based on the value of these coefficients, indicate which column(s) seem to be the

101
5.305414282688874
45.75485998468751
6.764233880099616

In [35]:
# most significant contributor to the LR model == Convenience Stores (as per our model)

most_sig_wt, idx = 0, 0
for index, wt in enumerate(best_model.coef_[0]): #YOUR CODE HERE inside the brackets -- use the coeff_ param of LinearRegression()

  if most_sig_wt < abs(wt):
    most_sig_wt = wt
    idx = index

In [37]:
most_sig_col = X.columns[idx]# Put the most significant column name here -- 1.5 of Gradescopetests
print(most_sig_col) # -- 1.5
# what is the intercept, for the best model as chosen by you
# Use intercept_ param of LinearRegression() and round it to 2 decimal places
intercept_val = best_model.intercept_# Put the value here -- 1.6 of Gradescope tests
print(intercept_val) # -- 1.6

Conv_stores
[43.55001725]